name: Execute

on:
  schedule:
    - cron: "0 7 * * *" # Runs on UTC

env:
  SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  CC: ${{ secrets.CC }}

jobs:
  build:
    name: Execute
    runs-on: ubuntu-latest
    container: clojure
    steps:
      - uses: actions/checkout@v4

      - name: Execute
        run: clojure -M -m birthdays
